export const aliasesedMatchers = [
  'is a number',
  '>',
  '>=',
  '<',
  '<=',
  'is text',
  'is text containing',
  'is text not containing',
  'is any of',
  'is not',
  'matches',
  'count =',
  'count >',
  'count >=',
  'count <',
  'count <=',
  'each has',
  'properties limited to',
  'is after',
  'is as early as',
  'is as late as',
  'is a date',
  'is earlier than',
  'is same date as',
  'is same date and time as',
  'is sorted',
  'is today',
  'is after today',
  'is before today',
];
