export const aliasesedMatchers = [
  { alias: 'is a number', argCount: 0 },
  { alias: '>', argCount: 1 },
  { alias: '>=', argCount: 1 },
  { alias: '<', argCount: 1 },
  { alias: '<=', argCount: 1 },
  { alias: 'is text', argCount: 0 },
  { alias: 'is text containing', argCount: 1 },
  { alias: 'is text not containing', argCount: 1 },
  { alias: 'is any of', argCount: Infinity },
  { alias: 'is not', argCount: 1 },
  { alias: 'matches', argCount: 1 },
  { alias: 'count =', argCount: 1 },
  { alias: 'count >', argCount: 1 },
  { alias: 'count >=', argCount: 1 },
  { alias: 'count <', argCount: 1 },
  { alias: 'count <=', argCount: 1 },
  { alias: 'each has a', argCount: 1 },
];
